### ISSUE TITLE
plugin-proposal-decorators regression

### ISSUE THREAD

**Issue by christopherjbaker** [artemirq/advanced-react-scripts#11]
### Is this a bug report?

Yes. There was a regression in babel@7.0.0-beta.37 that causes @babel/plugin-proposal-decorators and @babel/plugin-proposal-class-properties to not play well together. Many more detail can be found at https://github.com/babel/babel/issues/7177 Most people report fixing this by pinning to 7.0.0-beta.36 . I can confirm that fixes it for me as well.

The referenced `person.js` uses both decorators and class properties. If I remove either, this file is handled fine (though the next file that uses both catches it as well).

![image](https://user-images.githubusercontent.com/980338/36931233-9339da9e-1e66-11e8-9ed7-bcce9842b1d9.png)

### Did you try recovering your dependencies?

Yes

### Environment

1. `node -v`: v8.9.4
2. `npm -v`: 5.6.0
4. `npm ls react-scripts`: 0.3.46-release.0

**Comment by artembatura** [comment]
@christopherjbaker Thank you!

**Comment by artembatura** [comment]
@christopherjbaker Had to return to the beta.40 versions of babel packages, because of old versions have many bugs and one of them I met recently

It seems to me that the regression appeared due to the peculiarities in the code. If you want, you can show the code that caused the regression and we will try to solve this problem together. Either waiting for correction from the babel

**Comment by artembatura** [comment]
@christopherjbaker I try fix this bug in [this commit](https://github.com/artemirq/advanced-react-scripts/commit/ee91e50e3ff4dc8fcc226c373e21301ce4246bce)
Is there still such a bug?

**Comment by artembatura** [comment]
@christopherjbaker Hi! After [stop development](https://github.com/artemirq/advanced-react-scripts#this-repository-is-not-maintain-more-use-at-your-own-risk) of this fork, I [announced](https://github.com/artemirq/advanced-react-scripts/blob/next/README.md#now-i-start-work-on-tool-for-flexible-configuring-webpack-not-only-maybe), what I started developing new project for "configuring webpack (not only, maybe)"
Recently I publish [this project](https://github.com/artemirq/zero-scripts) and [written](https://github.com/artemirq/advanced-react-scripts#-update-the-project-which-i-announced-previously--now-on-github-its-zero-scripts) about this. It's would be a great, if you check my new project. At the moment i developed basic configuration and it's not ready for drop-replacement `react-script`
Zero Scripts is not replacement for `react-scripts`. [`preset.webpack-spa`](https://github.com/artemirq/zero-scripts/tree/master/packages/preset.webpack-spa) is replacement. But this project is can be used for any tool and any project type. Superior modularity by extensions not limit your technologies stack
I will be glad to hear your thoughts about this. Any suggestions and help are welcome 🙂
