### ISSUE TITLE
after install /bin/sh: advanced-react-scripts: command not found

### ISSUE THREAD

**Issue by jantos** [artemirq/advanced-react-scripts#15]
I think I am doing something fundamentally wrong.
I follow the simple installation step:
`yarn add advanced-react-scripts`

After that, I am assuming that I have to change my package.json to the following 

```
"scripts": {
    "start": "advanced-react-scripts start",
    "build": "advanced-react-scripts build",
    "test": "advanced-react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
```

but when I try to run `yarn run build` I get the following error: 

```
/usr/local/bin/node /usr/local/Cellar/yarn/1.3.2/libexec/bin/yarn.js run build
yarn run v1.3.2
$ advanced-react-scripts build
/bin/sh: advanced-react-scripts: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Process finished with exit code 1
```

I am pretty sure I am missing something, maybe somebody can guide me in the right direction.

**Comment by artembatura** [comment]
@jantos You don't need edit `package.json`. Using like original `react-scripts`:
```
    "scripts": {
        "start": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test --env=jsdom",
        "eject": "react-scripts eject"
    },
```

**Comment by jantos** [comment]
Thx @artemirq I changed it to what you said and now i get the following
```
./node_modules/redux-logger/dist/redux-logger.js
Module build failed: Thread Loader (Worker 0)
_core.types.cloneNode is not a function

```

Any idea why redux-logger would create such an issue? I saw someone else having the same error, but not due to that particular redux-logger package.

**Comment by artembatura** [comment]
@jantos With original `react-scripts` doesn't have this issue?

**Comment by jantos** [comment]
No, it doesn't.

**Comment by artembatura** [comment]
@jantos I don't know what the problem is... Maybe try delete folder `node-modules` and run `npm install`/`yarn install`?)

**Comment by jantos** [comment]
thx @artemirq I already tried that many times. No worries. I will keep on trying and if I find anything I will post it on here.

**Comment by artembatura** [comment]
@jantos Thanks. It will not be bad if you show the code that gives this error ;)

**Comment by artembatura** [comment]
@jantos Try use test version `0.3.46-release.4`. I met this problem and could be solved

**Comment by artembatura** [comment]
@jantos Now use latest version, `0.3.47-release.0`(test version deprecated)

**Comment by jantos** [comment]
@artemirq I will take a look at / try it out when I get back to the project. Had to move one and deal with some other stuff. You know how it is!
