### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by tatsujb** [artemirq/advanced-react-scripts#3]
App.js :
```
import React, { Component } from 'react';
import logo from './logo.svg';
import styles from './styles.module.sass';
import Carr from './Components/Special';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="styles.special">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
		<Carr />
      </div>
    );
  }
}

export default App;
```

Special.js : 
```
import React, { Component } from 'react';
import header from './header.module.sass';

class Special extends Component {
  render() {
    return (
        <div className="header.bloug">
		dsfgqfsfdfd!
		</div>
    );
  }
}

export default Special;
```
styles.module.sass :
```
.special {
   color: red;
}
```
header.module.sass : 
```
.special {
   color: green;
}
```
neither style is applied  : 
![image](https://user-images.githubusercontent.com/5132359/35388329-9bf7a38c-01d3-11e8-92b8-4e016fca45a5.png)

how am I doing this wrong?

I have no compiler error but it warns me that the loaded sass are never used :
```
 Compiled with warnings.

./src/Components/Special.js
  Line 2:  'header' is defined but never used  no-unused-vars

./src/App.js
  Line 2:  'logo' is defined but never used    no-unused-vars
  Line 3:  'styles' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

**Comment by artembatura** [comment]
@tatsujb 
In your code you use string instead of object. This shouldn't work. CSS(SASS) Modules require use object of importing styles
Use ```<p className={styles.special}>``` and ```<div className={header.special}>```. See more from [React CSS Modules guide](https://github.com/gajus/react-css-modules#css-modules)

Another problem is that you use the syntax of SCSS in the SASS file. SASS file need SASS syntax and the example:
```
.special
   color: red
```
[Сheck out the difference SASS & SCSS](https://www.sitepoint.com/whats-difference-sass-scss/)
