### ISSUE TITLE
add support for JS decorators too

### ISSUE THREAD

**Issue by ortonomy** [artemirq/advanced-react-scripts#6]
One of the best things about custom-react scripts is also the support for babel ES next decorators. Are going to add support here?

**Comment by artemirq** [comment]
@ortonomy I published `test` version to NPM `advanced-react-scripts@0.3.41`. For enable Decorators, add `REACT_APP_BABEL_STAGE_0=true` to config

**Сan you please check the work with Decorators?**

**Comment by artemirq** [comment]
[a335f20](https://github.com/artemirq/advanced-react-scripts/commit/a335f20c3dd07b32d60de0ed05082218984373b1)

**Comment by artembatura** [comment]
Closed at [fc57680](https://github.com/artemirq/advanced-react-scripts/commit/4340ed750684011de81f9631abeb5237c3a7cee3) & [a335f20](https://github.com/artemirq/advanced-react-scripts/commit/50e8acd2c0e427acd61b6390bf9d5644f383a7e3) & [9997655](https://github.com/artemirq/advanced-react-scripts/commit/fc5768083ef651f5cde08634d5bcb7e371e936b8)

**Comment by ortonomy** [comment]
Hey @artemirq -- thanks! Sorry I didn't reply over the weekend. I'll test it out this week.

**Comment by ortonomy** [comment]
> I published test version to NPM advanced-react-scripts@0.3.41. For enable Decorators, add REACT_APP_BABEL_STAGE_0=true to config

Did you already merge this into the active version on NPM?

**Comment by artembatura** [comment]
@ortonomy Now version 0.3.44-beta.3. Anyway check Readme
