### ISSUE TITLE
JS Decorators not supported

### ISSUE THREAD

**Issue by jkirkpatrick** [artemirq/advanced-react-scripts#7]
### Is this a bug report?

Yes

### Did you try recovering your dependencies?

Yes.
`yarn --version`
`1.3.2`

### Which terms did you search for in User Guide?

Issue only occurs with advanced-react-scripts, not custom-react-scripts.

### Environment

1. `node -v`:  8.9.4
2. `npm -v`: n/a
3. `yarn --version` (if you use Yarn): 1.3.2
4. `npm ls react-scripts` (if you haven’t ejected): n/a 

Then, specify:

1. Operating system: Ubuntu 16.04 LTS - (`uname -a` : `Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP`)
2. Browser and version (if relevant): Chrome 64

### Steps to Reproduce

(Write your steps here:)

1. yarn remove custom-react-scripts
2. yarn add advanced-react-scripts
3. change the line in .env from `REACT_APP_DECORATORS=true`  `REACT_APP_PROPOSAL_DECORATORS=true`
4. ensure the line in .env was unchanged `REACT_APP_BABEL_STAGE_0=true`
5. `yarn run start`

6. Steps 1,2 (above) then "Did you try recovering your dependencies?" and then 3,4,5 (above).

### Expected Behavior

Expected site would appear at http://localhost:3000

### Actual Behavior

Chrome tab opened with the following error:

Error: Decorating class property failed. Please ensure that proposal-class-properties is enabled and set to use loose mode. To use proposal-class-properties in spec mode with decorators, wait for the next major version of decorators in stage 2.
_initializerWarningHelper
http://localhost:3000/static/js/bundle.js:260742:65

### Reproducible Demo

Try one of the mobx demos with mobx decorators, error appears in the store.

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by artembatura** [comment]
@jkirkpatrick Can you please give me an example of the code that gives this error?
